### ISSUE TITLE
Wrong version is pulled

### ISSUE THREAD

**Issue by dannyjea** [demisto/demisto-sdk#1815]
When I issue pip3 install demisto-sdk it downloads demsito-sdk-0.2.6.tar.gz instead of the latest version. Running CentOS 8.
https://files.pythonhosted.org/packages/bc/a4/8d43b890699c88bdcb2f3efa19fdf2345ca4763160959d9268fa6b33b958/demisto-sdk-0.2.6.tar.gz

**Comment by dorschw** [comment]
Hi Danny, 
1. Please make sure you're using an updated version of pip
2. Please check you're using pip with pyhon3 (perhaps try calling `pip3 install demisto-sdk` instead)
3. if updating pip doesn't work, try `pip install --no-cache-dir --upgrade demisto-sdk` 

Please let us know whether these steps worked

**Comment by NCLdeveloper** [comment]
Hi, thanks for the response. It appears the issue was related to the version of the Python interpreter being used. As my starting point was a basic initial install of CentOS 8.5.2111, only python 3.6.8 was installed. I have now installed Python version 3.7.12 and used "python3.7 -m pip install demisto-sdk" which installed the correct version of demsito-sdk.
Thanks again for your support.
Regards
Danny
