### ISSUE TITLE
Download/Upload adds register_module_line calls to Script

### ISSUE THREAD

**Issue by icholy** [demisto/demisto-sdk#2207]
I'm using the sdk to backup and restore content from an XSOAR instance, but it's modifying the script content.

## What version of the SDK are you using?

1.6.8

## What did you do?

1. Create "EchoHello" Automation Script using the Web Editor.

![image](https://user-images.githubusercontent.com/943597/176275203-af083909-d0fc-4d86-a94e-ed2ed91875a5.png)

2. Download script to local content repo:

``` sh
$ demisto-sdk download -i EchoHello -o ./Packs/MyStuff
```

3. Upload script from content repo:

``` sh
$ demisto-sdk upload -i ./Packs/MyStuff/Scripts/EchoHello
```

## What did you expect to happen?

The code in the Web Editor remains unchanged.

![image](https://user-images.githubusercontent.com/943597/176275243-1a1f8b6a-ccfa-44d8-a677-46e43b81bde6.png)

## What happened instead?

The code in the Web Editor contains:

![image](https://user-images.githubusercontent.com/943597/176275347-e39e5c13-7f17-4107-8b59-8552b9c7bba6.png)

**Comment by dorschw** [comment]
Hi @icholy, this is a feature allowing easier debugging.

(cc @yaakovi)

**Comment by dorschw** [comment]
Hi, the link describes CommonServerPython, the `register_module_line` is not part of CommonServerPython but a later feature, added around late 2021. 

This is considered expected behavior, so I'm closing this issue. If you encounter any problem with the content, please feel free to reopen it and attach the details.
